-- Feature 12: payment receipts — a justificatif attached to each payment.
-- Pure business data persisted and readable via API: NO PDF, printing, signature,
-- QR code, email or WhatsApp (document generation is a future feature).
-- Conventions: docs/database-conventions.md (snake_case, uuid ids, timestamptz).
--
-- payment_receipts is linked to exactly one payment: the business rules allow at
-- most ONE ACTIVE receipt per payment. The partial unique index enforces it for
-- ACTIVE rows (same pattern as ux_service_closures_preparation_active in V10);
-- soft-deleting the receipt releases the slot so a new receipt may be created for
-- the same payment while the other rules still hold.
--
-- receipt_number (REC-YYYY-NNNN) is generated by the backend, never by the
-- client, and is globally unique: the plain unique index guarantees it. Numbers
-- of soft-deleted rows are NEVER reused — the per-year sequence only moves
-- forward (the API always computes max(number) over ALL rows, deleted included).
--
-- amount, payment_method, payment_date and payment_reference are a SNAPSHOT of
-- the payment at issuance: the receipt keeps its own history and never depends on
-- the current payment row (payment_reference mirrors payments.reference and is
-- therefore nullable).
--
-- payment_id references payments without ON DELETE CASCADE: payments are only
-- soft-deleted and must keep their receipt history. The receipt never modifies
-- the payment.
-- The index on payment_id serves the paymentId filter of the list endpoint
-- (same rationale as idx_payments_proposal_id in V7).

CREATE TABLE payment_receipts (
    id                uuid           PRIMARY KEY,
    payment_id        uuid           NOT NULL REFERENCES payments (id),
    receipt_number    varchar(30)    NOT NULL,
    amount            numeric(14, 2) NOT NULL,
    payment_method    varchar(30)    NOT NULL,
    payment_date      date           NOT NULL,
    payment_reference varchar(255),
    created_at        timestamptz    NOT NULL,
    updated_at        timestamptz    NOT NULL,
    version           bigint         NOT NULL,
    deleted_at        timestamptz
);

CREATE INDEX idx_payment_receipts_payment_id ON payment_receipts (payment_id);

CREATE UNIQUE INDEX ux_payment_receipts_receipt_number
    ON payment_receipts (receipt_number);

CREATE UNIQUE INDEX ux_payment_receipts_payment_active
    ON payment_receipts (payment_id) WHERE deleted_at IS NULL;