-- Feature 13: invoices — a financial document linked to one payment.
-- Business data persisted and readable via API only: NO PDF, printing, signature,
-- QR code, email or WhatsApp (document generation is a future feature).
-- Conventions: docs/database-conventions.md (snake_case, uuid ids, timestamptz).
--
-- invoices is linked to exactly one payment: the business rules allow at most ONE
-- ACTIVE invoice per payment. The partial unique index enforces it for ACTIVE rows
-- (same pattern as ux_payment_receipts_payment_active in V11); soft-deleting the
-- invoice releases the slot so a new invoice may be created for the same payment.
--
-- invoice_number (FAC-YYYY-NNNN) is generated by the backend, never by the client,
-- and is globally unique: the plain unique index guarantees it. Numbers of
-- soft-deleted rows are NEVER reused — the per-year sequence only moves forward
-- (the API always computes max(number) over ALL rows, deleted included).
--
-- amount, payment_method, payment_date and payment_reference are a SNAPSHOT of the
-- payment at issuance (immutable history, never recalculated from the payment);
-- payment_reference mirrors payments.reference and is therefore nullable.
-- issued_at stamps when the invoice was emitted (server-side only).
--
-- payment_id references payments without ON DELETE CASCADE: payments are only
-- soft-deleted and must keep their invoice history. The invoice never modifies
-- the payment. The index on payment_id serves the paymentId list filter
-- (same rationale as idx_payment_receipts_payment_id in V11).

CREATE TABLE invoices (
    id                 uuid           PRIMARY KEY,
    payment_id         uuid           NOT NULL REFERENCES payments (id),
    invoice_number     varchar(30)    NOT NULL,
    amount             numeric(14, 2) NOT NULL,
    payment_method     varchar(30)    NOT NULL,
    payment_date       date           NOT NULL,
    payment_reference  varchar(255),
    issued_at          timestamptz    NOT NULL,
    created_at         timestamptz    NOT NULL,
    updated_at         timestamptz    NOT NULL,
    version            bigint         NOT NULL,
    deleted_at         timestamptz
);

CREATE INDEX idx_invoices_payment_id ON invoices (payment_id);

CREATE UNIQUE INDEX ux_invoices_invoice_number
    ON invoices (invoice_number);

CREATE UNIQUE INDEX ux_invoices_payment_active
    ON invoices (payment_id) WHERE deleted_at IS NULL;